[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' app.netlify.com netlify-cdp-loader.netlify.app; font-src *; frame-src 'self' app.contentful.com; frame-ancestors 'self' app.contentful.com"
	X-Frame-Options = "ALLOW-FROM https://app.contentful.com"